application: test-results-hrd
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /dashboards
  static_dir: static-dashboards

- url: /testfile/delete
  script: main.py
  login: admin

- url: /.*
  script: main.py
